With proper escape

diff --git a/stack b/stack
--- a/stack
+++ b/stack
@@ -39,27 +39,26 @@ stack_ns=$(yq -e e '.ns' $infile 2>/dev/null) || stack_ns="${infile%.*}"
 stack_name=$(yq -e e '.name' $infile 2>/dev/null) || stack_name="${stack_ns}"
 trace "Working with stack '${stack_name}@${stack_ns}' from $(yq e '.files | .[] | select(.)' $infile| wc -l) files"
 for compose_file in $(yq e '.files | .[] | select(.)' $infile); do
-  stack="${stack}$(cat $compose_file)\n---\n"
+  stack="${stack}$(cat $compose_file)"$'\n---\n'
 done;
 
 stack_revision=$(echo -e "$stack" | md5sum | head -c 5)
 
 current_stack=.docker-stack/${stack_ns}.yml
 
-
 trace "Working in $current_stack"
 
 mkdir -p .docker-stack
 
-echo -e "$stack"| yq -e e '.' - >/dev/null || (
+echo "$stack"| yq -e e '.' - >/dev/null || (
   dump_file="${current_stack}-debug.yml"
-  echo -e "$stack" > $dump_file
+  echo "$stack" > $dump_file
   abort "Find trace in $dump_file"
 )
 
 header="${stack_name}:${stack_ns} @${stack_revision} (dspp v${DSPP_VERSION}-${DSPP_HASH})"
 
-compiled=$(echo -e "$stack" \
+compiled=$(echo "$stack" \
   | yq -j ea 'del(.x-*)' - \
   | yq -P eval-all '. as $item ireduce ({}; . *+ $item ) |
     sortKeys(..) |
@@ -71,7 +70,7 @@ compiled=$(echo -e "$stack" \
 
 if [[ $action == "deploy" ]] ; then
 
-  [ -f "$current_stack" ] && diff -q "$current_stack" <(echo -e "$compiled") || abort "Change detected, please compile first"
+  [ -f "$current_stack" ] && diff -q "$current_stack" <(echo "$compiled") || abort "Change detected, please compile first"
 
   docker stack deploy --with-registry-auth --compose-file - $stack_name < "$current_stack"
   docker service ls
@@ -80,21 +79,21 @@ fi
 if [[ $action == "compile" ]] ; then
   in=$current_stack
   [ ! -f "$in" ] && in=/dev/null
-  diff -q "$in" <(echo -e "$compiled") && abort "No changes detected" 0  || ( diff -y <(echo -e "current stack\n---"; cat "$in")  <(echo -e "next stack\n---"; echo -e "$compiled") | colordiff | most)
+  diff -q "$in" <(echo "$compiled") && abort "No changes detected" 0  || ( diff -y <(echo -e "current stack\n---"; cat "$in")  <(echo -e "next stack\n---"; echo "$compiled") | colordiff | most)
 
   read -p "Confirm [y/N]: " commit
   commit=$(echo -n ${commit:-n} | tr '[:upper:]' '[:lower:]')
 
   [ $commit != "y" ] && exit 1;
 
-  echo -e "$compiled" > $current_stack
+  echo "$compiled" > $current_stack
   trace "Stack wrote in $current_stack"
 fi
 
 
 
 if [[ $action == "validate" ]] ; then
-  echo -e "$compiled" | yq -P e '' -
+  echo "$compiled" | yq -P e '' -
   exit 0;
 fi
 
