With secrets

diff --git a/stack b/stack
--- a/stack
+++ b/stack
@@ -4,6 +4,7 @@ set -e
 
 DSPP_VERSION=1.0.1
 DSPP_HASH=$(md5sum "$0" | head -c 5)
+YQ_VERSION=$(yq -V | cut -d' ' -f 3)
 
 abort() { trace "$1"; exit ${2:-1}; }
 usage() { abort "Usage: $0 \n\t-f [stack-file.yml] compile|deploy\n\t[-v] show version"; }
@@ -24,18 +25,26 @@ while getopts "vf:" o; do
     esac
 done
 
+( expr $YQ_VERSION \>= 4.9 > /dev/null) && echo "Found yq@$YQ_VERSION" || abort "Invalid yq version\n"
 shift $((OPTIND-1))
 
 # validate args
 [ ! -f "$infile" ] && usage
 
 action=$1   # deploy or compile
+filter=$2
+
 
 
 # start things
 trace "Processing stack in '$infile'"
 
 stack_ns=$(yq -e e '.ns' $infile 2>/dev/null) || stack_ns="${infile%.*}"
+if [ ! -z "$filter" ] ; then
+  stack_ns="${stack_ns}.${filter}"
+  echo "Filter stack for '${filter}'"
+fi
+
 stack_name=$(yq -e e '.name' $infile 2>/dev/null) || stack_name="${stack_ns}"
 trace "Working with stack '${stack_name}@${stack_ns}' from $(yq e '.files | .[] | select(.)' $infile| wc -l) files"
 for compose_file in $(yq e '.files | .[] | select(.)' $infile); do
@@ -58,15 +67,39 @@ echo "$stack"| yq -e e '.' - >/dev/null || (
 
 header="${stack_name}:${stack_ns} @${stack_revision} (dspp v${DSPP_VERSION})"
 
+
+# expand all references
+# strip all comments
+# merge all documents
+# sort & reduce remaining
+
 compiled=$(echo "$stack" \
-  | yq -j ea 'del(.x-*)' - \
-  | yq -P eval-all '. as $item ireduce ({}; . *+ $item ) |
-    sortKeys(..) |
-    {"version":.version, "configs":.configs, "networks":.networks, "volumes":.volumes, "services":.services} |
-    del( .[] | select(. == null) ) |
-    . headComment="'"$header"'"
+  | yq -P eval-all 'explode(.)
+    | ... comments=""
+    | del(.x-*)
+    | . as $item ireduce ({}; . *+ $item )
+    | sortKeys(..)
+    | {"version":.version, "configs":.configs, "secrets":.secrets, "networks":.networks, "volumes":.volumes, "services":.services}
+    | del( .[] | select(. == null) )
+    | . headComment="'"$header"'"
   ' - )
 
+
+if [ ! -z "$filter" ] ; then
+  # strip all filtered services
+
+  compiled=$(echo "$compiled" \
+    | yq e '
+     {
+        "version"  : .version,
+        "configs"  : .configs,
+        "secrets"  : .secrets,
+        "networks" : .networks,
+        "volumes"  : .volumes,
+        "services" : .services | with_entries(select(.key == "*'"$filter"'*"))
+    } | del( .[] | select(. == null or length == 0) )
+    ' - )
+fi
 
 if [[ $action == "deploy" ]] ; then
 
