With tracing tools

diff --git a/stack b/stack
--- a/stack
+++ b/stack
@@ -2,7 +2,9 @@
 
 set -e
 
-usage() { echo "Usage: $0 -f [stack-file.yml] compile|deploy" 1>&2; exit 1; }
+abort() { trace "$1"; exit ${2:-1}; }
+usage() { abort "Usage: $0 -f [stack-file.yml] compile|deploy"; }
+trace() { echo $1 1>&2; }
 
 
 # parse cmdline
@@ -25,18 +27,24 @@ action=$1   # deploy or compile
 
 
 # start things
-echo "Processing stack in '$infile'"
+trace "Processing stack in '$infile'"
 
 stack_ns=$(yq -e e '.ns' $infile 2>/dev/null) || stack_ns="${infile%.*}"
 stack_name=$(yq -e e '.name' $infile 2>/dev/null) || stack_name="${stack_ns}"
 
-echo "Working with stack '$stack_name'@'$stack_ns' from $(yq e '.files | .[] | select(.)' $infile| wc -l) files"
+trace "Working with stack '$stack_name'@'$stack_ns' from $(yq e '.files | .[] | select(.)' $infile| wc -l) files"
 for compose_file in $(yq e '.files | .[] | select(.)' $infile); do
   stack="${stack}$(cat $compose_file)\n---\n"
 done;
 
 current_stack=.docker-stack-${stack_ns}.yml
 
+
+echo -e "$stack"| yq -e e '.' - >/dev/null || (
+  dump_file="${current_stack}-debug.yml"
+  echo -e "$stack" > $dump_file
+  abort "Find trace in $dump_file"
+)
 
 
 compiled=$(echo -e "$stack" | yq -j ea '
@@ -50,7 +58,7 @@ compiled=$(echo -e "$stack" | yq -j ea '
 
 if [[ $action == "deploy" ]] ; then
 
-  [ -f "$current_stack" ] && diff -q "$current_stack" <(echo -e "$compiled") || (echo "Change detected, please compile first" && exit 1)
+  [ -f "$current_stack" ] && diff -q "$current_stack" <(echo -e "$compiled") || abort "Change detected, please compile first"
 
   docker stack deploy --with-registry-auth --compose-file "$current_stack" $stack_name
   docker service ls
@@ -59,7 +67,7 @@ fi
 if [[ $action == "compile" ]] ; then
   in=$current_stack
   [ ! -f "$in" ] && in=/dev/null
-  diff -q "$in" <(echo -e "$compiled") && echo "No changes detected" || ( diff -y <(echo -e "current stack\n---"; cat "$in")  <(echo -e "next stack\n---"; echo -e "$compiled") | colordiff | most)
+  diff -q "$in" <(echo -e "$compiled") && abort "No changes detected" 0  || ( diff -y <(echo -e "current stack\n---"; cat "$in")  <(echo -e "next stack\n---"; echo -e "$compiled") | colordiff | most)
 
   read -p "Confirm [y/N]: " commit
   commit=$(echo -n ${commit:-n} | tr '[:upper:]' '[:lower:]')
@@ -67,7 +75,7 @@ if [[ $action == "compile" ]] ; then
   [ $commit != "y" ] && exit 1;
 
   echo -e "$compiled" > $current_stack
-  echo "Stack wrote in $current_stack"
+  trace "Stack wrote in $current_stack"
 fi
 
 
